# Generated by Django 4.1.6 on 2024-03-12 19:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0030_coursegroup_tasks_coursegroup_tasks_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_geo', models.TextField(blank=True)),
                ('options', models.TextField(blank=True)),
                ('options_geo', models.TextField(blank=True)),
                ('answer', models.IntegerField(blank=True)),
                ('xp', models.IntegerField(blank=True, default=5)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursegroup')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('content_geo', models.TextField(blank=True)),
                ('code', models.TextField(blank=True)),
                ('answers', models.TextField()),
                ('xp', models.IntegerField(blank=True, default=5)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursegroup')),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_projects.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubmittedMarkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks_projects.marktask')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
