# Generated by Django 4.1.6 on 2024-02-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
