# Generated by Django 4.1.6 on 2024-02-24 19:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_coursegroup_tasks_coursegroup_tasks_geo'),
        ('tasks_projects', '0002_task_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task_geo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('code', models.TextField(blank=True)),
                ('answers', models.TextField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.coursegroup')),
            ],
        ),
    ]
