# Generated by Django 4.1.6 on 2024-02-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_coursegroup_tasks_coursegroup_tasks_geo'),
        ('tasks_projects', '0003_task_geo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Task_geo',
            new_name='TaskGeo',
        ),
    ]
