# Generated by Django 4.1.6 on 2024-02-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_projects', '0004_rename_task_geo_taskgeo'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='xp',
            field=models.IntegerField(blank=True, default=5),
        ),
        migrations.AddField(
            model_name='taskgeo',
            name='xp',
            field=models.IntegerField(blank=True, default=5),
        ),
    ]
