# Generated by Django 4.1.6 on 2024-02-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_projects', '0005_task_xp_taskgeo_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='content_geo',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='TaskGeo',
        ),
    ]
