# Generated by Django 4.1.6 on 2023-02-24 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='first_name',
            field=models.CharField(default=models.CharField(max_length=150, unique=True), max_length=150),
        ),
    ]
