# Generated by Django 4.1.6 on 2023-02-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_first_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
