# Generated by Django 4.1.6 on 2023-04-24 17:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_newuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='friend',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
