# Generated by Django 4.1.6 on 2023-07-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_remove_course_requirements_remove_course_silabus'),
        ('users', '0022_newuser_friends'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='courses',
            field=models.ManyToManyField(blank=True, to='courses.course'),
        ),
    ]
