# Generated by Django 4.1.6 on 2023-07-25 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_usercourse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='courses',
        ),
    ]
