# Generated by Django 4.1.6 on 2023-07-26 10:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_remove_newuser_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='purchased_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
