# Generated by Django 4.1.6 on 2023-07-26 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_usercourse_purchased_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='title',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
