# Generated by Django 4.1.6 on 2023-08-13 19:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_newuser_friend_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='sended_friend_request',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
