# Generated by Django 4.1.6 on 2023-09-05 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_remove_newuser_friend_request_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='profile_picture',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
