# Generated by Django 4.1.6 on 2023-09-09 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_course_main_text_course_price'),
        ('users', '0033_paymentprocess'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentProcess',
            new_name='PaymentInProcess',
        ),
    ]
