# Generated by Django 4.1.6 on 2023-09-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_rename_paymentprocess_paymentinprocess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentInProcess',
        ),
    ]
