# Generated by Django 4.1.6 on 2023-09-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_alter_usercoursepage_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoursepage',
            name='page',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
