# Generated by Django 4.1.6 on 2023-10-20 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_usercoursepage_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
