# Generated by Django 4.1.6 on 2023-11-12 19:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_remove_usercourse_level_remove_usercourse_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(4)]),
        ),
    ]
