# Generated by Django 4.1.6 on 2023-11-20 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_promocode_userpromocode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='promocode',
            old_name='content',
            new_name='promo_code',
        ),
    ]
