# Generated by Django 4.1.6 on 2023-11-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_rename_content_promocode_promo_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocode',
            name='sale',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
