# Generated by Django 4.1.6 on 2024-01-25 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_reportuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportUser',
        ),
    ]
