# Generated by Django 4.1.6 on 2024-01-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_reportuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
