# Generated by Django 4.1.6 on 2024-02-13 07:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_newuser_is_banned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='user_name',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
