# Generated by Django 4.1.6 on 2024-02-27 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_newuser_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='xp',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
