# Generated by Django 4.1.6 on 2024-04-21 20:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_coursebundle_roadmap'),
        ('users', '0055_newuser_xp'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBundleCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course_bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursebundle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
