# Generated by Django 4.1.6 on 2024-05-09 18:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0056_userbundlecourse'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entered', models.DateField(default=django.utils.timezone.now)),
                ('read', models.DateField(default=django.utils.timezone.now)),
                ('task', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
