# Generated by Django 4.1.6 on 2024-05-09 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0057_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='entered',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='read',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='task',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
