# Generated by Django 4.1.6 on 2024-05-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_useractivitylog_entered_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActivityLog',
        ),
    ]
