# Generated by Django 4.1.6 on 2024-02-13 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_alter_newuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='email',
            field=models.EmailField(error_messages={'blank': 'This email se.', 'required': 'This email asdfasdf.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
