# Generated by Django 4.1.6 on 2024-05-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0060_useractivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='entered',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='read',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='task',
            field=models.DateField(),
        ),
    ]
