# Generated by Django 4.1.6 on 2024-05-09 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_useractivitylog_entered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='entered',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='read',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='useractivitylog',
            name='task',
            field=models.DateField(blank=True, null=True),
        ),
    ]
