# Generated by Django 4.1.6 on 2024-05-09 19:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0062_alter_useractivitylog_entered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivitylog',
            name='entered',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='read',
        ),
        migrations.RemoveField(
            model_name='useractivitylog',
            name='task',
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='activity_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useractivitylog',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
