# Generated by Django 4.1.6 on 2024-05-09 20:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0063_remove_useractivitylog_entered_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='date_created',
            field=models.DateTimeField(default=datetime.date.today),
        ),
    ]
