# Generated by Django 4.1.6 on 2024-05-09 20:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0064_alter_useractivitylog_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useractivitylog',
            name='date_created',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
