# Generated by Django 4.1.6 on 2023-04-30 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Room',
        ),
    ]
