# Generated by Django 4.1.6 on 2023-04-30 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0004_rename_rooms_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='room',
            name='sender',
        ),
        migrations.AddField(
            model_name='room',
            name='accessed_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
