# Generated by Django 4.1.6 on 2023-04-30 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_room_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='reseiver',
            new_name='receiver',
        ),
    ]
