# Generated by Django 4.1.6 on 2023-05-12 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0013_alter_room_accessed_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
        migrations.AlterField(
            model_name='room',
            name='accessed_users',
            field=models.ManyToManyField(limit_choices_to={'is_active': True}, to=settings.AUTH_USER_MODEL),
        ),
    ]
