# Generated by Django 4.1.6 on 2024-02-03 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img_link',
            field=models.TextField(blank=True),
        ),
    ]
