# Generated by Django 4.1.6 on 2023-02-08 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('requirements', models.TextField(max_length=150)),
                ('silabus', models.TextField(max_length=500)),
                ('description', models.TextField(max_length=500)),
            ],
        ),
    ]
