# Generated by Django 4.1.6 on 2023-02-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=5000000),
        ),
        migrations.AlterField(
            model_name='course',
            name='requirements',
            field=models.TextField(max_length=15000),
        ),
        migrations.AlterField(
            model_name='course',
            name='silabus',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.TextField(max_length=1000),
        ),
    ]
