# Generated by Django 4.1.6 on 2023-02-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_description_alter_course_requirements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=5),
        ),
    ]
