# Generated by Django 4.1.6 on 2023-07-25 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_usercourse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCourse',
        ),
    ]
