# Generated by Django 4.1.6 on 2023-08-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_level_course_topics'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='main_text',
            field=models.TextField(blank=True),
        ),
    ]
