# Generated by Django 4.1.6 on 2023-08-06 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_course_main_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='big_description',
            field=models.TextField(blank=True),
        ),
    ]
