# Generated by Django 4.1.6 on 2023-09-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_coursegroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='code',
            field=models.TextField(blank=True),
        ),
    ]
