# Generated by Django 4.1.6 on 2023-09-07 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_coursegroup_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='main_text',
        ),
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10),
        ),
    ]
