# Generated by Django 4.1.6 on 2023-09-23 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0015_remove_course_main_text_course_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='main_text_geo',
            field=models.TextField(blank=True),
        ),
    ]
