# Generated by Django 4.1.6 on 2023-10-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_coursegroup_main_text_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/'),
        ),
    ]
