# Generated by Django 4.1.6 on 2023-10-20 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_coursegroup_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='keyword',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
