# Generated by Django 4.1.6 on 2023-10-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_alter_coursegroup_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursegroup',
            name='image',
            field=models.FileField(blank=True, upload_to='image/'),
        ),
    ]
