# Generated by Django 4.1.6 on 2023-10-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_alter_coursegroup_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursegroup',
            name='image',
        ),
        migrations.CreateModel(
            name='CourseGroupImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='image/')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.coursegroup')),
            ],
        ),
    ]
