# Generated by Django 4.1.6 on 2023-10-21 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_remove_coursegroup_image_coursegroupimages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseGroupImages',
            new_name='CourseGroupImage',
        ),
    ]
