# Generated by Django 4.1.6 on 2023-11-12 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0023_delete_coursegroupimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='big_description_geo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='description_geo',
            field=models.TextField(blank=True, max_length=5000000),
        ),
    ]
