# Generated by Django 4.1.6 on 2023-11-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_course_big_description_geo_course_description_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level_geo',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
