# Generated by Django 4.1.6 on 2023-11-14 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_course_topics_geo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='course',
            name='topics_geo',
        ),
    ]
