# Generated by Django 4.1.6 on 2024-01-22 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_remove_course_topics_remove_course_topics_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10),
        ),
    ]
