# Generated by Django 4.1.6 on 2024-01-31 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_course_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price_geo',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10),
        ),
    ]
