# Generated by Django 4.1.6 on 2024-02-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_course_price_geo'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='tasks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursegroup',
            name='tasks_geo',
            field=models.TextField(blank=True),
        ),
    ]
