# Generated by Django 4.1.6 on 2024-04-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_coursegroup_tasks_coursegroup_tasks_geo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseBundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('courses', models.ManyToManyField(blank=True, to='courses.course')),
            ],
        ),
    ]
