# Generated by Django 4.1.6 on 2024-04-19 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0031_coursebundle'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
