# Generated by Django 4.1.6 on 2024-04-19 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_coursebundle_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AddField(
            model_name='coursebundle',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10),
        ),
    ]
