# Generated by Django 4.1.6 on 2024-04-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_coursebundle_price_coursebundle_real_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebundle',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='coursebundle',
            name='real_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10, null=True),
        ),
    ]
