# Generated by Django 4.1.6 on 2024-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0034_alter_coursebundle_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
