# Generated by Django 4.1.6 on 2024-04-19 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0035_coursebundle_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='level',
            field=models.TextField(blank=True, max_length=100),
        ),
    ]
