# Generated by Django 4.1.6 on 2024-04-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0036_coursebundle_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebundle',
            name='level',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
