# Generated by Django 4.1.6 on 2024-04-19 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0037_alter_coursebundle_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='description_geo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursebundle',
            name='level_geo',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='coursebundle',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
