# Generated by Django 4.1.6 on 2024-04-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0038_coursebundle_description_geo_coursebundle_level_geo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='big_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='coursebundle',
            name='big_description_geo',
            field=models.TextField(blank=True),
        ),
    ]
