# Generated by Django 4.1.6 on 2024-04-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0040_coursebundle_roadmap'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='bundle_sale',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
