# Generated by Django 4.1.6 on 2024-05-26 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0041_coursebundle_bundle_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=200)),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='lessons',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='summary_geo',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='tags',
            field=models.ManyToManyField(related_name='course_tags', to='courses.tag'),
        ),
    ]
