# Generated by Django 4.1.6 on 2024-08-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0042_tag_course_lessons_course_summary_course_summary_geo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebundle',
            name='tags',
            field=models.ManyToManyField(related_name='bundle_tags', to='courses.tag'),
        ),
    ]
